---
services:
  filebeat:
    image: jahrik/arm-filebeat:latest
    hostname: "{{.Node.Hostname}}-filebeat"
    # root so filebeat can read container logs and docker.sock
    user: root
    networks:
      - elk
    configs:
      - source: fb_config
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - filebeat:/usr/share/filebeat/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      - /var/log/:/var/log/:ro
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-elasticsearch}
      - KIBANA_HOST=${KIBANA_HOST:-kibana}
    command: ["--strict.perms=false"]
    deploy:
      mode: global

networks:
  elk:
    name: elk
    driver: overlay
    external: true

volumes:
  filebeat:

configs:
  fb_config:
    file: ./filebeat.yml
